FROM python:3.12.2-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    postgresql-client \
    libpq-dev \
    python3-dev \
    libxslt1-dev \
    libldap2-dev \
    libsasl2-dev \
    libssl-dev \
    g++ \
    git \
    gcc \
    wkhtmltopdf && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

#docker buildx build -f Dockerfile-k3s-python3 --platform linux/amd64 -t six-odoo-k3s-python3:latest .
