FROM six-odoo-k3s-python3:latest

# Set environment variables
ENV ODOO_VERSION=18.0 \
    ODOO_HOME=/opt/odoo \
    ODOO_USER=odoo \
    ODOO_LOCAL_CONFIG=odoo-k3s.conf \
    ODOO_CONFIG=/etc/odoo/odoo.conf \
    ODOO_EXTRA_ADDONS=/etc/addons

# Create Odoo user and directories
RUN useradd -m -d $ODOO_HOME -U -r -s /bin/bash $ODOO_USER
RUN mkdir -p /var/lib/odoo /etc/odoo $ODOO_EXTRA_ADDONS && chown -R $ODOO_USER:$ODOO_USER /var/lib/odoo /etc/odoo $ODOO_EXTRA_ADDONS

# Copy Odoo source code
COPY --chown=$ODOO_USER:$ODOO_USER . $ODOO_HOME
# Copy the Odoo configuration file
COPY --chown=$ODOO_USER:$ODOO_USER $ODOO_LOCAL_CONFIG $ODOO_CONFIG

# Install Python dependencies
WORKDIR $ODOO_HOME
RUN pip install --upgrade pip setuptools wheel Cython
RUN pip install psycopg2
RUN pip install python-jose
RUN pip install --no-cache-dir -r requirements.txt

# Expose Odoo port
EXPOSE 8069

# Define entrypoint
USER $ODOO_USER
#CMD ["python3", "odoo-bin", "--config", "/etc/odoo/odoo.conf"]
#CMD ["python3", "odoo-bin", "--config", "/etc/odoo/odoo.conf", "-d", "six_odoo", "--init=base", "--stop-after-init"]
CMD ["python3", "odoo-bin", "--config", "/etc/odoo/odoo.conf", "-d", "six_odoo", "--without-demo=all"]

#docker buildx build -f Dockerfile-k3s --platform linux/amd64 -t six-odoo-k3s:18.0.1 .
#docker inspect six-odoo-k3s:18.0.1 | grep Architecture
#docker run -d --name six-odoo -p 8069:8069 -v /Users/yuping/Work/odoo/addons-external/oca/tutorials:/etc/addons six-odoo:18.0
#docker exec -it six-odoo /bin/bash