[options]
; This is the database configuration
db_host = 192.168.0.240
db_port = 5432
db_user = six_odoo_admin
db_password = six_odoo_password
db_name = six_odoo

; Specify the add-ons path
addons_path = /opt/odoo/addons,/etc/addons

; Log file
; logfile = /Users/yuping/Work/odoo/six-odoo.log

; run the odoo for the first time: python3 odoo-bin -c odoo.conf -d six_odoo -i base
; run the odoo for the following run time: python3 odoo-bin -c odoo.conf

; root@ecs-six-innovation:~# psql -h 10.42.0.1 -U six_odoo_admin -d six_odoo

